#!/usr/bin/env python3
"""Fetch live USD/MXN and USD/CAD interbank rates (Yahoo Finance) -> fx_live.js.

Run by GitHub Actions every 15 min (see .github/workflows/update.yml).
The PV dashboard pages fetch fx_live.js from raw.githubusercontent.com and
overlay it as today's FX point, because free daily sources (Frankfurter/ECB,
open.er-api.com) publish yesterday's close.

Idempotent; on partial failure the previously written rate for the other
currency pair is kept. If both fetches fail, the old file is left untouched
and the script exits non-zero.
"""
import json
import time
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent / "fx_live.js"
URLS = {
    "mxn": "https://query1.finance.yahoo.com/v8/finance/chart/MXN=X?range=1d&interval=1d",
    "cad": "https://query1.finance.yahoo.com/v8/finance/chart/USDCAD=X?range=1d&interval=1d",
}


def fetch_price(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=15) as r:
        j = json.load(r)
    return float(j["chart"]["result"][0]["meta"]["regularMarketPrice"])


def read_prev():
    if not OUT.exists():
        return {}
    try:
        for line in OUT.read_text().splitlines():
            if line.startswith("window.FX_LIVE"):
                return json.loads(line.split("=", 1)[1].strip().rstrip(";"))
    except Exception:
        pass
    return {}


def main():
    rates = {}
    for k, u in URLS.items():
        try:
            rates[k] = round(fetch_price(u), 4)
        except Exception as e:
            print(f"warn: {k} fetch failed: {e}")
    if not rates:
        raise SystemExit("all fetches failed; keeping previous fx_live.js")
    prev = read_prev()
    prev.update(rates)
    prev["t"] = int(time.time() * 1000)
    OUT.write_text(
        "// auto-generated by fetch_fx.py (GitHub Actions) — DO NOT EDIT\n"
        f"window.FX_LIVE = {json.dumps(prev)};\n"
    )
    print(f"ok: {rates}")


if __name__ == "__main__":
    main()
